---
name: China Pictorial
locales: [en]
subdomain: china_pictorial
domains: [demo-chinapictorial.siz.yt, chinapictorial.locomotivehosting.com, china_pictorial.locomotivehosting.com]
seo_title: china pictorial, A windows to the nation.
meta_keywords: some meta keywords
meta_description: some meta description
timezone: UTC
